use_small_heuristics = "Max"
comment_width = 120
condense_wildcard_suffixes = true
force_explicit_abi = false
format_strings = true
format_macro_matchers = true
hard_tabs = true
merge_imports = true
match_block_trailing_comma = true
max_width = 120
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
overflow_delimited_expr = true
unstable_features = true
version = "Two"
normalize_doc_attributes = true
